import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}`}
      >
        <section className="w-full flex gap-4 p-2">
          <SideBar />
          <div>
            <h1 className="text-2xl font-bold mb-4">
              Welcome to PlanGo
            </h1>
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
